import "../blocks/header/header.js";
import "../blocks/slider/slider.js";
import "../blocks/about/about.js";
import "../blocks/pan/pan.js";
import "../blocks/videos/videos.js";
import "../blocks/order/order.js";
import "../blocks/footer/footer.js";
import "../blocks/details/details.js";
import "../blocks/ambient/ambient.js";